import { Language } from './types';

export const translations = {
  en: {
    title: "Prompt Engineer",
    subtitle: "CRISPE Framework",
    inputDetails: "Input Details",
    clearAll: "Clear All",
    generateBtn: "Generate Professional Prompt",
    optimizing: "Optimizing...",
    required: "* Instruction field is required",
    readyTitle: "Ready to Optimize",
    readyDesc: "Fill in the CRISPE fields on the left and hit the optimize button to transform your ideas into a professional prompt.",
    optimizingTitle: "Optimizing your prompt via Gemini...",
    optimizingDesc: "Applying role hardening, instruction clarification, and structural formatting.",
    resultTitle: "Optimized Prompt",
    copy: "Copy Output",
    copied: "Copied",
    generatedBy: "Generated by Gemini 2.5 Flash • Optimization Framework by CRISPE",
    tabEn: "English Prompt",
    tabCn: "Chinese Prompt",
    fields: {
      context: { label: "Context", placeholder: "e.g., I am preparing a marketing campaign for a new coffee brand...", description: "Provide the background or scenario." },
      role: { label: "Role", placeholder: "e.g., Marketing Genius", description: "Who should the AI act as?" },
      instruction: { label: "Instruction", placeholder: "e.g., Write 5 catchy slogans...", description: "What do you want the AI to do?" },
      specifics: { label: "Specifics", placeholder: "e.g., Tone should be energetic, under 10 words each...", description: "Style, format, and constraints." },
      process: { label: "Process", placeholder: "e.g., First brainstorm keywords, then draft slogans...", description: "Specific steps the AI should follow (Optional)." },
      example: { label: "Example", placeholder: "e.g., \"Wake up to greatness.\"", description: "Provide reference examples (Optional)." },
    }
  },
  cn: {
    title: "提示词工程师",
    subtitle: "CRISPE 框架",
    inputDetails: "输入详情",
    clearAll: "清空重置",
    generateBtn: "生成专业提示词",
    optimizing: "正在优化...",
    required: "* 指令字段 (Instruction) 必填",
    readyTitle: "准备就绪",
    readyDesc: "在左侧填写 CRISPE 字段，点击生成按钮，将您的想法转化为结构完美的专业提示词。",
    optimizingTitle: "正在通过 Gemini 优化...",
    optimizingDesc: "正在进行角色强化、指令清晰化和结构格式化。",
    resultTitle: "优化结果",
    copy: "复制内容",
    copied: "已复制",
    generatedBy: "由 Gemini 2.5 Flash 生成 • CRISPE 优化框架",
    tabEn: "英文提示词 (English)",
    tabCn: "中文提示词 (Chinese)",
    fields: {
      context: { label: "背景 (Context)", placeholder: "例如：我正在准备一个新的咖啡品牌营销活动...", description: "提供任务背景或场景。" },
      role: { label: "角色 (Role)", placeholder: "例如：营销天才", description: "希望 AI 扮演什么角色？" },
      instruction: { label: "指令 (Instruction)", placeholder: "例如：写5个朗朗上口的口号...", description: "你希望 AI 做什么？" },
      specifics: { label: "细节 (Specifics)", placeholder: "例如：语气要充满活力，每个在10个字以内...", description: "风格、格式和限制条件。" },
      process: { label: "过程 (Process)", placeholder: "例如：首先头脑风暴关键词，然后起草...", description: "AI 应遵循的具体步骤（可选）。" },
      example: { label: "示例 (Example)", placeholder: "例如：“唤醒伟大。”", description: "提供参考示例（可选）。" },
    }
  }
};

export const getTranslation = (lang: Language) => translations[lang];
